
server {

    listen 443 ssl;
    server_name mradouan.42.fr;

    root /var/www/html;
    index index.php;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000; # Send this PHP request to the container named wordpress on port 9000
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #$document_root=/var/www/html , $fastcgi_script_name=/index.php  URL=https://localhost/index.php
    }

    location = /adminer {
    include fastcgi_params;
    fastcgi_pass adminer:9000;
    fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
    }
}

