services:
  nginx:
    build:
      context: requirements/nginx
    depends_on:
      - wordpress

    ports:
      - "443:443"
    container_name: nginx

    restart: on-failure

    volumes:
      - wordpress-data:/var/www/html

    networks:
      - inception-network


  wordpress:
    build:
      context: requirements/wordpress
    
    container_name: wordpress

    restart: on-failure

    depends_on:
      - mariadb
    environment:
      
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mariadb:3306
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_AU_USER: ${WP_AU_USER}
      WP_AU_EMAIL_USER: ${WP_AU_EMAIL_USER}
      WP_AU_PASSWORD: ${WP_AU_PASSWORD}

    volumes:
      - wordpress-data:/var/www/html

    networks:
      - inception-network
    

  mariadb:
    build: 
      context: requirements/mariadb
    
    container_name: mariadb

    restart: on-failure

    volumes:
      - mariadb-data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
    networks:
      - inception-network


  portfolio:
    build:
      context: requirements/bonus/static_website
    
    container_name: portfolio

    ports:
      - 80:80

    restart: on-failure

  adminer:
    build:
      context: requirements/bonus/adminer
    
    container_name: adminer
  
    networks:
      - inception-network

    restart: on-failure

    depends_on:
      - mariadb
  
  redis:
    build:
      context: requirements/bonus/redis
    
    container_name: redis

    networks:
      - inception-network

    restart: on-failure
  
  portainer:
    build:
      context: ./requirements/bonus/portainer

    container_name: portainer

    restart: always

    ports:
      - "9000:9000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mradouan/data/portainer:/data

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mradouan/data/mariadb

  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mradouan/data/wordpress

networks:
  inception-network: